version: '3.3'

services:
  game-service:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   match_db:
    #     condition: service_healthy
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://match-db:3306/gamedb?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: root
      JDBC_DATABASE_USERNAME: root
    networks:
      - game-network
      - game-db-network
    volumes:
      - maven_packages:/root/.m2


networks: 
  game-network:
    name: game-network
  game-db-network:
    name: game-db-network

volumes:
  maven_packages:
    name: maven_packages