version: '3.3'

services:
  match_db:
    build: 
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55


  authentication_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      match_db:
        condition: service_healthy
    image: authentication-service:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://match_db:3306/match_pool?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: root
      JDBC_DATABASE_USERNAME: root