version: '3.3'

services:
  game_service:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   match_db:
    #     condition: service_healthy
    restart: always
    ports:
      - 8080:8080
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://match_db:3306/match_pool?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: root
      JDBC_DATABASE_USERNAME: root
    networks:
      - game-network
      - game-db-network


networks: 
  game-network:
    name: game-network
  game-db-network:
    name: game-db-network